@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "ServerClientHandler",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1694949796 { 
   	label=ServerClientHandler
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   ServerClientHandler1694949796[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ServerClientHandler</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   bufferedReader: BufferedReader [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   bufferedWriter: BufferedWriter [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   clientUsername: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   isCoordinator: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   peers: ArrayList&lt;ServerClientHandler&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   socket: Socket [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- Log(message: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ Send(message: String)</TD></TR>
<TR><TD ALIGN="LEFT" >- SendDM(dm: String)</TD></TR>
<TR><TD ALIGN="LEFT" >- broadcastMessage(messageToSend: String)</TD></TR>
<TR><TD ALIGN="LEFT" >- closeEverything()</TD></TR>
<TR><TD ALIGN="LEFT" >- handleMessage(message: String)</TD></TR>
<TR><TD ALIGN="LEFT" >- initialise()</TD></TR>
<TR><TD ALIGN="LEFT" >+ makeCoordinator()</TD></TR>
<TR><TD ALIGN="LEFT" >- quit()</TD></TR>
<TR><TD ALIGN="LEFT" >- removeClientHandler()</TD></TR>
<TR><TD ALIGN="LEFT" >+ run()</TD></TR>
<TR><TD ALIGN="LEFT" >- sendHelp()</TD></TR>
<TR><TD ALIGN="LEFT" >- sendUserList()</TD></TR>
<TR><TD ALIGN="LEFT" >- timeStamp(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1827877273 { 
   	label=ServerHandler
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   ServerHandler1827877273[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ServerHandler</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   handlers: ArrayList&lt;ServerClientHandler&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   serverSocket: ServerSocket [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- Log(message: String)</TD></TR>
<TR><TD ALIGN="LEFT" >- closeServerSocket()</TD></TR>
<TR><TD ALIGN="LEFT" >+ startServer()</TD></TR>
<TR><TD ALIGN="LEFT" >- timeStamp(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
ServerHandler1827877273 -> ServerClientHandler1694949796[label="handlers
[0..*]"];
    
}
@enduml